driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: fedora-20
  - name: ubuntu-12.04
  - name: ubuntu-14.10

suites:
  #
  # mysql2_chef_gem
  #
  - name: client50-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.0'
       provider: 'mysql'
    includes: [
      'centos-5.10'
    ]

  - name: client51-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.1'
       provider: 'mysql'
    includes: [
      'centos-6.5',
      'ubuntu-10.04'
    ]

  - name: client55-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.5'
       provider: 'mysql'
    includes: [
      'centos-6.5',
      'debian-7.0',
      'ubuntu-12.04',
      'ubuntu-14.04'
    ]

  - name: client56-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.6'
       provider: 'mysql'
    includes: [
      'centos-5.10',
      'centos-6.5',
      'centos-7.0',
      'ubuntu-14.04'
    ]

  - name: client57-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.7'
       provider: 'mysql'
    includes: [
      'centos-5.10',
      'centos-6.5',
      'centos-7.0'
    ]

## MariaDB
  - name: client55-mariadb
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
        provider: 'mariadb'
      mariadb:
       install:
        version: '5.5'
    includes: [
      #'debian-7.0',
      #'centos-6.5',
      #'centos-7.0',
      'fedora-20',
      #'ubuntu-12.04',
      'ubuntu-14.04'
    ]
