#<% require 'kitchen-sync' %>
---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  google_client_email: <%= ENV['GOOGLE_CLIENT_EMAIL'] %>
  google_key_location: <%= ENV['GOOGLE_KEY_LOCATION'] %>
  google_project: <%= ENV['GOOGLE_PROJECT'] %>
  joyent_username: <%= ENV['SDC_CLI_ACCOUNT'] %>
  joyent_keyfile: <%= ENV['SDC_CLI_IDENTITY'] %>
  joyent_keyname: <%= ENV['SDC_CLI_KEY_ID'] %>
  joyent_url: <%= ENV['SDC_CLI_URL'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  flavor_id: <%= ENV['EC2_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_solo
  # require_chef_omnibus: 11.16.4
  require_chef_omnibus: 12.0.3

platforms:
- name: centos-5.8
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-5-8-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-6-5-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: centos-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-7-0-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: amazon-2014.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-9a6ed3f2
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: fedora-20
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: fedora-20-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: debian-7.0
  driver_plugin: gce
  driver_config:
    image_name: debian-7-wheezy-v20131120
    zone: <%= ENV['GCE_ZONE'] %>
    area: <%= ENV['GCE_AREA'] %>
    network: <%= ENV['GCE_NETWORK'] %>
    username: <%= ENV['GCE_USERNAME'] %>
    public_key_path: <%= ENV['GCE_PUBLIC_KEY_PATH'] %>
    ssh_key: <%= ENV['GCE_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-10-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-12-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-14-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

suites:
  #
  # mysql2_chef_gem
  #
  - name: client50-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.0'
       provider: 'mysql'
    includes: [
      'centos-5.8'
    ]

  - name: client51-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.1'
       provider: 'mysql'
    includes: [
      'centos-6.5',
      'ubuntu-10.04'
    ]

  - name: client55-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.5'
       provider: 'mysql'
    includes: [
      'centos-6.5',
      'fedora-20',
      'debian-7.0',
      'ubuntu-12.04',
      'ubuntu-14.04'
    ]

  - name: client56-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.6'
       provider: 'mysql'
    includes: [
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20',
      'ubuntu-14.04'
    ]

  - name: client57-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.7'
       provider: 'mysql'
    includes: [
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20'
    ]

## MariaDB
  - name: client55-mariadb
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
        provider: 'mariadb'
      mariadb:
       install:
        version: '5.5'
    includes: [
      #'debian-7.0',
      #'centos-6.5',
      #'centos-7.0',
      'fedora-20',
      #'ubuntu-12.04',
      'ubuntu-14.04'
    ]
