" The greatest ever vimrc file
runtime! debian.vim

:filetype plugin on
:filetype plugin indent on

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

execute pathogen#infect()

" Vim5 and later versions support syntax highlighting. Uncommenting the
" following enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

if has("autocmd")
   " Drupal special php files.
   augroup module
       autocmd BufRead,BufNewFile *.module set filetype=php
       autocmd BufRead,BufNewFile *.install set filetype=php
       autocmd BufRead,BufNewFile *.test set filetype=php
       autocmd BufRead,BufNewFile *.profile set filetype=php
   augroup END
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set autowrite		" Automatically save before commands like :next and :make
set hidden          " Hide buffers when they are abandoned
set mouse=a		    " Enable mouse usage (all modes)
set hlsearch        " Highlight search terms
set autoindent      " Keeps indent on the next line
set smartindent     " Drupal requirement

" Save temp files in the tmp directory
set backupdir=~/.tmp,/tmp
set swapfile
set dir=~/.tmp,/tmp

" John commands
set expandtab
set tabstop=2
set shiftwidth=2
set backspace=start,indent,eol

highlight Comment ctermfg=darkyellow
hi FoldColumn  ctermfg=lightred ctermbg=black
hi Folded      ctermfg=lightred ctermbg=black

let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabContextDefaultCompletionType = "<c-x><c-o>"
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1

" PHP stuff
autocmd FileType php let php_sql_query=1     " highlights interpolated variables in sql strings and does sql-syntax highlighting
autocmd FileType php let php_htmlInStrings=1 " does exactly that. highlights html inside of php strings
autocmd FileType php let php_noShortTags=1   " discourages use oh short tags. c'mon its deprecated remember
autocmd FileType php let php_folding=1       " automagically folds functions & methods.

" autocomplete funcs and identifiers for languages
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete

" User maps
map <C-L> :w !php -l %<CR>
map <C-E> :Explore<CR>
map <C-K> :Errors<CR>

:highlight RedundantSpaces ctermbg=red guibg=red
:match RedundantSpaces /\s\+$\| \+\ze\t/

" set clipboard=unnamed

" Pass arguments to phpcs binary
let g:syntastic_phpcs_conf=" --standard=Drupal --extensions=php,module,inc,install,test,profile,theme"
let g:syntastic_check_on_open=1

" Line numbers
:set number

" Indent PHP case in switch statements properly.
:let g:PHP_vintage_case_default_indent = 1

" Set the leader key for NERDCommenter (highlight then ,ci to toggle comments)
:let mapleader = ','
